# This file was generated by GoReleaser. DO NOT EDIT.
cask "crossplane-mcp" do
  version "0.8.5"

  on_macos do
    on_arm do
      sha256 "d2ce109b71d66431803cc6cb9fa15a20a9831cee515a0ae519d0bb67368a7c70"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "46b45d6f761c65fea7271d0c7043ef0b62ed1a04a255cfdcce023d49fe11e8c0"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c5314b5f807722b6f90ea62b39524eb445fafc1310f7832c9a6adb9dd55d0eb4"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e3359919adaaab34d630e52d3d103a88edc88105348ace5ac24c15b01012d691"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "crossplane-mcp"
  desc "Read-only diagnostic MCP server for Crossplane"
  homepage "https://github.com/briferz/crossplane-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crossplane-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crossplane-mcp"]
    end
  end

  # No zap stanza required
end
