# This file was generated by GoReleaser. DO NOT EDIT.
cask "crossplane-mcp" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "0d9a74cb2e2a0d8a2f391c4a317c47e64cd378071f0bb9de3b30cffb3df95ca6"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0283e8c86e349726758e25a459419a368fa8a47deb06e7e2f4b6ea52262879a6"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c81a53067a2afa166939d6155fc2044734d592e1d5e4289d0c0e0e267ff3b86b"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb7c0ed45b06a3d922e98230accc4f9d7798cfe9f7109914fd1f7b087b066017"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crossplane-mcp"
  desc "Read-only diagnostic MCP server for Crossplane"
  homepage "https://github.com/briferz/crossplane-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crossplane-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crossplane-mcp"]
    end
  end

  # No zap stanza required

end
