# This file was generated by GoReleaser. DO NOT EDIT.
cask "crossplane-mcp" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "e1de2f407866e3775b4a3b5081153dcb200837b6d12e2622863c95f01295351a"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51911f251a9e6e0aa66299b09e83d48a67f2598a7eb8adbcf1aad11699028d58"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41a4675f854b64bd2d0988250c3c21b449ec433e188dead47321d13906400daa"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a78cac72d126c8d0ea72796d5c1ea86c291cbdb47e1a026d073d802eb3eebc73"
      url "https://github.com/briferz/crossplane-mcp/releases/download/v#{version}/crossplane-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crossplane-mcp"
  desc "Read-only diagnostic MCP server for Crossplane"
  homepage "https://github.com/briferz/crossplane-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crossplane-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crossplane-mcp"]
    end
  end

  # No zap stanza required

end
